[package]
name = "mandelbrot-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mandelbrot-rs"
path = "src/main.rs"

[dependencies]
rayon = "1.5"